### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by Aldaviva** [JorTurFer/EasyWakeOnLan#3]
The interface that `EasyWakeOnLanClient` implements is currently spelled [`IEasyWakeOnLanCient`](https://github.com/JorTurFer/EasyWakeOnLan/blob/b65c996bfc8cb96e20dc7d4a869485887235fa8d/src/EasyWakeOnLan/IEasyWakeOnLanClient.cs#L9) instead of `IEasyWakeOnLanClient`.

The readme also has some typos in the [**Dependency Injection** section](https://github.com/JorTurFer/EasyWakeOnLan#dependency-inyection):
- The section is currently spelled `Inyection` instead of `Injection`.
- Both types described in the section are spelled `Cient` instead of `Client`.

**Comment by JorTurFer** [comment]
HI,
You are right, thanks for reporting! This library hasn't got support currently and that change breaks the previous versions so I should release a major version to solve it, and I won't do it. Sorry :(
If you are interested, you can take the code (it is really simple) and put it directly in your project.
